### PR TITLE
Upgrade symfony process dependency

### PR DESCRIPTION
**Pull request by Th3Mouk**
Compatibility is ensured between the two majors.

Can you please tag a new version after this merge.

Thanks

### CODE REVIEW

**Comment by Th3Mouk** [comment]
Hello @brianium are u still the maintainer ?

**Comment by brianium** [comment]
@Th3Mouk thanks for the PR :) - I've not really been doing much with PHP these days - so I'm not really maintaining peridot things. I think most people have started using [kahlan](https://github.com/kahlan/kahlan). Seems to be a much more actively developed testing tool with similar goals to peridot. Maybe @ezzatron or @austinsmorris have thoughts, but I'm not currently certain of peridot's future.

**Comment by Th3Mouk** [comment]
Thanks for the advice. We will migrate our test suite, if you can please merge this one.

Have a nice day

**Comment by ezzatron** [comment]
PR looks fine, thanks!

**Pull request merged**
